name: "Events - Features"

on:
  workflow_dispatch:
  push:
  pull_request:
  schedule:
    - cron: "*/2 * * * *" # Runs every 2 minutes

jobs:
  event-info-job:
    runs-on: ubuntu-latest

    steps:
      - name: Print Trigger Event
        run: echo "My trigger is ${{ github.event_name }} event"